<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<LangVersion>13</LangVersion>
		<AssemblyName>CodeChicken.DiffPatch</AssemblyName>
		<Version>1.1.0</Version>

		<NewRootDir>..\PatchReviewer\DiffPatch</NewRootDir>
		<BaseIntermediateOutputPath>$(NewRootDir)\obj\new\</BaseIntermediateOutputPath>
		<BaseOutputPath>$(NewRootDir)\bin\new\</BaseOutputPath>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="$(NewRootDir)\**\*.cs" Exclude="$(NewRootDir)\bin\**;$(NewRootDir)\obj\**" />
	</ItemGroup>
	
</Project>